### ISSUE TITLE
请问现在的网易云music真实连接还能获取吗？

### ISSUE THREAD

**Issue by qssq** [mrdong916/DAPI#1]
我在网上倒腾1天了，没思绪。

**Comment by qssq** [comment]
嗯，怎么弄呢，

**Comment by mrdong916** [comment]
查看文档吧，只要有songid就可以获取到播放地址

**Comment by qssq** [comment]
....咋了，是不是真的不能了对补？我之前是根据接口得到id然后查询详情，但是也没看到想要的信息。

**Comment by mrdong916** [comment]
请加入QQ群579621905，与我联系吧

**Comment by zhouyu1993** [comment]
@mrdong916 QQ群579621905 怎么禁止加入了
