### ISSUE TITLE
接口网易云只返回了一首歌

### ISSUE THREAD

**Issue by bjason** [mrdong916/DAPI#2]

**Comment by mrdong916** [comment]
请求的数据是什么，需快速解决，加群联系我吧

**Comment by bjason** [comment]
请求的是歌单全部歌曲

________________________________

**Comment by mrdong916** [comment]
具体的请求数据

**Comment by bjason** [comment]
{"TransCode":"020111","OpenId":"123456789","Body":{"SongListId":21329331}}

之前都是可以的

________________________________

**Comment by mrdong916** [comment]
请求的歌曲ID请使用字符串

**Comment by mrdong916** [comment]
刚刚测试过，请求没有问题，请仔细检查你的代码
